# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
