# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:aab0b50a3ce43a41621fc7040a379cc57174059aec8f9c17a90176649a0c1ab1

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
