# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:d43a8878689311f841a1967f899f54db56877bf6b426fd7ff870ac1a6fd1dce4

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
