# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:6d819e9ab067efcf712993b23455cc100ee5585919bb297ea5a109ac00cb626e

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
