# values.yaml
secrets:
  name: my-secrets

image:
  repository: jellyfin/jellyfin
  tag: latest@sha256:1edf3f17997acbe139718f252a7d2ded2706762390d787a34204668498dbc5f6

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
