# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: rolling@sha256:1a8a4b11972b2e62671b49949c622b8cb1110e2b5c77199ac795a6d79fe106e8

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
