# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: rolling@sha256:4394dff2311238bf5c31e006872122ed4e5f6bf042d33528d80acd44a09c57f7

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
