# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/prowlarr
  tag: rolling@sha256:e2459e199564ab852c6e677e951cef36c172a8e71a0e1c90665631b5a0c57438

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
