# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/bazarr
  tag: rolling@sha256:6e2fab9cca3096714795458aec222da5e2e5cde07ed07e439f9879c9de3b5b94

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
