# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/bazarr
  tag: rolling@sha256:0949a30fb6e6703a63aaa9775760b8af820f7871f6a9aa9207e2ea00fd855e2c

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
