# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:ddd6be1bf38a1402537ad4086d8dd3290c62ffc477f3a9b47c59a7c8ba01bbc0

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
