# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:6c5512140f0328a9704aab9287a5cfa004e90a128abf710eee0f0081c616e76e

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
