# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:9ec9aa2e497bf01112a481c5e9f1220ca3df792d4b8eea82c625ea7040a9440f

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
