# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:ad3b69806eebfdb0e6eb9d70177875c478eee46a967fece97d29c5f02ed36faf

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
