# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:2e89f4f0f1badf3651e3ee893436b58d1fdc622e6e1949bb73c6255b0e7db339

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
