# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:f2f0d1e44ef31b56efa0bd3a66b3b4d1be254504f569efe4adf0741b93505dd2

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
