# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:38ed509a8a4736372f747422eb8dd163c68e51c655601d324c141719b5d61d7b

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
