# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:95ad3cb17601f3e4e887e9dd32440aeaa607dbd09f3db040f4e8292a383a52ae

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
