# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:a85298f8da91aa1c24f656f6ae7d8d817b6a97bc4f06e2945e406975f0e21b03

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
