# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:889b922d4358b9be55239995f7933538faa9c4a3773da69445bcac8a005336d9

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
