# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:917345a88d4cdbcc08c85e22b6d82b1306c4065c5bf9bc79a009f876338e6e1c

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
