# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:d9e2b96ff9c3e773145602787219f4c347ef8064ddec1614b5405e37555a7cee

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
