# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/cloudtube
  tag: latest@sha256:551c645e94345c2a239e4fd0f121269aedb1487317e6dfcf69cfeba00e7739a3

env:
  TZ: Africa/Nairobi

user:
  PUID: 132
  PGID: 136
