# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:5fb338e4d2eaa76c00496c8474906a129b9182a9aace8ebdd9657571de762c70

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
