# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:cd5d4334b596c1b727d012dc309771b548a18bd3bd8dc7ab289030f331a7f4ed

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
