# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:a0451ef055400fd38cb6173792c61cbbef5685759ec656e1f54ef6f8b0195b66

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
