# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:aa31e673f9ff4e5fd56551766c12e77964cba93c0abc96d736ee23cd856cc38e

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
