# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:0d8075060168231bb89dce9407cc446720d2b928fe527c25a13962eee7b301bc

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
