# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/rhee876527/wikiless
  tag: latest@sha256:0f74d10a1da9f3b81f2e873072b031e1caf77d4d30f8d00bc204b1b2bd6c98d0

env:
  TZ: Africa/Nairobi

valkey:
  SERVICE: valkey
