# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:73fbdba72dcde5fec16264e63a9daba7829b5c2806a75615463a67117b100de3

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
