# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:22bbf7e924dd929b756147d8110664c3e2da37c59516b249945ab1d63657be29

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
