# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:5e08c0eefd2770d1d29395c4f84fe5bf7dfc3a986598021306a5d8ac017a3989

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
