# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/radarr
  tag: rolling@sha256:10f94c85f605d42e5e78de928f24758b5750a4e99eee8d0ef9ff150f7a2df033

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
