# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:242f2034875c568592223d72ed2a155220f1b704abde150bde05d41e793abcb8

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001