# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:796096f41bce220b703013defa06650dfd87050b4051bc5eca26a050f51f8037

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001