# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:3260ae03f6b46ef6b624b9734829fa9e631fb6df44bc960003a802aec207acf3

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001