# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:03199db255a98e078d5185f7d6eb645671b5837c4c015e69f0a0a2b3a04cc670

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001