# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:fc4b4a22447c04b3b3a4e6afbd89af8f627ba5221c79a9779f8ed77667e7bab1

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001