# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:eab1e4c2133139e54c3eb4027ff696dd9980c04aa2b28994b7bb9b59582a6516

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001