# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:c69ced01f6c70a52585f0a920dd534c91edcd65902472361ebff186e2d5547c1

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001