# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:813d86129f33fc22abb908366be71e5765a381bf0f08c220b1f2694610ff724f

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001