# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:ec36b9769b93c6fdccfb71a81df3bd635eb72aa5e9660fdad9237529f7699da2

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001