# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:5e75565cc54f5e2ed3d5903f149dc5bde32fabc2fb710de5d6e050897f683830

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001