# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:ca64c4d003303ecc043cc624933511c275eefcecd871969ae97e3d6ebcff153c

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001