# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:d608bd6aa4a447f1b8ad5ae2a164f6af6bb9d6f4a51425df4021477e45d6f82c

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001