# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:6a15a2f4a5bbaf833e235692cb7ec40a120bd72c3508b246c70e159e84c4311c

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001