# values.yaml
secrets:
  name: my-secrets

image:
  repository: lscr.io/linuxserver/nextcloud
  tag: latest@sha256:9686da278d09e938e716c90d6b79eb03937db4099442714116466eb909bb8f7f

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001