# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:67c90fe48b64ab5774aa8c139f48c144fbaf81764ca9268997c88b0278a1de91

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
