# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:733c25efc9c7d195cc11974b75abff935e30c33d1f88dbcf0a6accd772718608

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
