# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:8945a21397f91de6538abbf6c171ed329a16f1a256884fc8d6449d7716e48425

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
