# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:09dfc123bd7c118ed086471b42d17ed57964827beffeb8d7f012dae3d2608545

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
