# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:6a4ca3058a439d96805b7340ae84dacce6ade5456c24a1dde0bc6415ad76c1c6

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
