# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:42286096985cba935e9a8bbb69d7c3ad41fa36eaa69c55057f6b2acaa1404fd3

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
