# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:341e651b6138d745014a41b6f3f33f69033497c42d9d42aa532f45c0890d1a99

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
