# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:8d1655e92c354814bab388f7fa0b69bfa101e29b9e3579e79500cda78315d2f2

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
