# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:74b24c5e6390bef69486d22282ece69e2e0ac3546cc1093d816edbd87471b9e2

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
