# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:b88ef002ab1d9a901766f9eb59779089a74e8f444477e0151fa8cd1f91a02006

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:1be494495248d53e3558b198a1c704e6b559d5e99fe4c926e14a8ad24d76c6fa

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
