# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:0355eac00e7ec52decf6586f03209a9aeb8c63a1ecbf200835fdb3e2247ced02

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
