# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:6f3a875c64bd804d1ccf2fe3c8df35e985b75ffbf0322f216544e79912fabab2

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
