# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:8d77102a0d2c615e88c5184868dc2c32cd361413dbc104abc301f54079fd40a2

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
