# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:d5a965f005818c16014198e2684b4705f686fe6b298482029bdf72095ec0d73d

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
