# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:5cf43eea89b334f0b34ec03eef03a432e1734dbc13e980878ea1442c50391c7e

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
