# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:7dfe4abf855ee9ef946c057211179dbc97e05d49a15db11d937c84b1e412098a

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:c106a0c03bcb23cbdf9febe693114cb7800646b11ca8b303aee7409de005faa8

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
