# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:d5a54dde3968851d6a15f394bd1d64e0ac5e440e6b21c73bddf215dfcd82fe16

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:b4ee67d73e00393e712accc72cfd7003b87d0fcd63f0eba798b23251bfc9c394

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
