# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:95e59f5ba7d48b4c7ee92f2705907e52c5b98715b0d8c4802863322a502a8c4a

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
