# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:c25c6b671382f0464318b2de3b142f1c9fe3721e46fdad027f4d6caf399728ea

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:bef37d06d4856710973ee31dd1eac1482e4c8e6e7b847f999ad25433e646587b

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
