# values.yaml
secrets:
  name: my-secrets

image:
  repository: searxng/searxng
  tag: latest@sha256:60055af6f2f1ca14b488d9c0f47a019d1dbaf15b4f6547a7194253bf2ab94744

valkeyImage:
  repository: valkey/valkey
  tag: alpine@sha256:68677f85c863830af7836ff07c4a13b7f085ebeff62f4dedb71499ca27d229f2

user:
  PUID: 126
  PGID: 130

env:
  TZ: Africa/Nairobi
