# values.yaml
secrets:
  name: my-secrets

image:
  repository: miniflux/miniflux
  tag: 2.2.15-distroless@sha256:e94547c3620b79e3e00aab001dae9a710020f189c9bb5373c251bf05ed47a4df

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 1001
  PGID: 1001