# values.yaml
secrets:
  name: my-secrets

image:
  repository: miniflux/miniflux
  tag: 2.2.16-distroless@sha256:82af042befc298b89cc4488910ec8bead3632a1070de7b72ee6a117df41b71f3

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 1001
  PGID: 1001