# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:14c0581eb2010e09d18ae24b3766a2e7d97644034532808e615f8131936e9ee3

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
