# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:d0764a01b1efacf7a8489ec3859b823dba4922e5e1f6403ed2f3466aadb78da6

postgresImage:
  repository: postgres
  tag: 18-alpine

user:
  PUID: 133
  PGID: 137
