# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:fa8d521b58f926829970f6ec1812adb6df348f0244ec7ca18efcf416c49b9edd

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
