# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:3a2afede5c58365d50e73077d63347cb1ef33ea8f5cd11d5c719c8e4e2f837dc

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
