# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:5ce16245fc6d12827a80a3d80b9afa6e018955bb355dab48b0ef4f99805f7d3b

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
