# values.yaml
secrets:
  name: my-secrets

image:
  repository: quay.io/invidious/invidious
  tag: master-arm64@sha256:e12280e903a9239e8ada87d5d9243fc484e23cc6403f0f1519589e831e51423e

postgresImage:
  repository: postgres
  tag: 15-alpine

user:
  PUID: 133
  PGID: 137
