# values.yaml
image:
  repository: ghcr.io/cycneuramus/containers
  pinned: redlib@sha256:4b607fd58f2c170d9bbf073bfedbe570c5b6f29c7e72b3a2285e86d5c7f98af9

user:
  PUID: 121
  PGID: 127

theme:
  DEFAULT: rosebox
