# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/sonarr
  tag: rolling@sha256:3597fd572f4599c67abbeb8afd3cb85bce8a9e389f0779b7ea1273781544d15c

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
