# values.yaml
secrets:
  name: my-secrets

image:
  repository: ghcr.io/home-operations/sonarr
  tag: rolling@sha256:22651c750eedb091f6d76ade95dbecae0eeafe2b55432c3b8d8b042e8745f344

env:
  TZ: Africa/Nairobi

user:
  PUID: 1001
  PGID: 1001
